Update parquet to 1.12.3 in PXF
Update parquet to 1.12.3 (latest version with hadoop-client-2.x)
* Add support for ZSTD compression
* Temporary declare LZO as not supported. It causes following error in both current and in pre-upgrade builds:
   ```
   ERROR:  PXF server error : Class com.hadoop.compression.lzo.LzoCodec was not found  (seg1 10.11.0.131:6000 pid=2567556)
   ```
* Add tests to cover different types of compression