Update parquet to 1.15.2 in PXF (#52)
### Update parquet to 1.15.2: 

* Add support for ZSTD compression
* Add support for LZ4_RAW codec
* More optimal memory usage in compression codecs
* Temporary declare LZO as not supported. It causes following error in both current and in pre-upgrade builds:
   ```
   ERROR:  PXF server error : Class com.hadoop.compression.lzo.LzoCodec was not found  (seg1 10.11.0.131:6000 pid=2567556)
   ```
* Add tests to cover different types of compression

Dependency tree changes are small:
```
+--- org.apache.parquet:parquet-column:1.15.1
|    +--- org.apache.parquet:parquet-common:1.15.1
|    |    +--- org.apache.parquet:parquet-format-structures:1.15.1
|    +--- org.apache.parquet:parquet-encoding:1.15.1
|    |    +--- org.apache.parquet:parquet-common:1.15.1 (*)
+--- org.apache.parquet:parquet-hadoop:1.15.1
|    +--- org.apache.parquet:parquet-column:1.15.1 (*)
|    +--- org.apache.parquet:parquet-format-structures:1.15.1 (*)
|    +--- org.apache.parquet:parquet-common:1.15.1 (*)
|    +--- org.xerial.snappy:snappy-java:1.1.10.7
|    +--- io.airlift:aircompressor:2.0.2
|    +--- commons-pool:commons-pool:1.6
|    +--- com.github.luben:zstd-jni:1.5.6-6
+--- org.apache.parquet:parquet-jackson:1.15.1
+--- org.apache.parquet:parquet-generator:1.15.1
+--- org.apache.parquet:parquet-pig:1.15.1
|    +--- org.apache.parquet:parquet-column:1.15.1 (*)
|    +--- org.apache.parquet:parquet-hadoop:1.15.1 (*)
|    +--- org.apache.parquet:parquet-common:1.15.1 (*)
\--- org.apache.parquet:parquet-format:2.10.0
```

It has its own thrift library shaded. It doesn't depend on protobuf.
`parquet-hadoop` in fact expects that there is `hadoop-client`, `hadoop-common`, `hadoop-annotations` and  `hadoop-mapreduce-client-core` provided.